import Head from "next/head";

type Props = {
  title: string;
  children: React.ReactNode;
};

const Page: React.FC<Props> = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-0 flex min-h-screen flex-col bg-TwoIBlue p-8 text-4xl font-bold text-white">
        {children}
      </main>
    </>
  );
};

export default Page;
